### ISSUE TITLE
About the accuracy of the age

### ISSUE THREAD

**Issue by Jarvis-Cai** [ywu94/Tencent-Ads-Algo-Comp-2020#9]
Hi, old iron, thanks for share. I have tried your code, it seems that the accuracy of age can reach about 0.43.

**Comment by ywu94** [comment]
Hi which model do you try? The ResGRU one can achieve 0.48 for age accuracy.

**Comment by MyrnaQiu** [comment]
Does the accuracy refer to the test set after submission?

**Comment by ywu94** [comment]
> Does the accuracy refer to the test set after submission?

Yes and the online score is almost the same as that of offline validation, difference is at 1e-4 level.

**Comment by MyrnaQiu** [comment]
> > Does the accuracy refer to the test set after submission?
> 
> Yes and the online score is almost the same as that of offline validation, difference is at 1e-4 level.

Which one can achieve 0.48? And what're the parameters? Thanks!
